POST http://localhost:3001/users
Content-Type: application/json

{
  "first_name": "Jane",
  "last_name": "Jane",
  "email": "Jane@email.com",
  "password": "jane"
}

###
POST http://localhost:3001/auth
Content-Type: application/json

{
  "email": "bob@bobby.com",
  "password": "bob"
}